import { Occurrence, OccurrenceStatus, OccurrenceType } from '../types';

export const seedOccurrences: Occurrence[] = [
  {
    id: 'OCC-1715894361',
    schoolUnit: 'Escola Municipal Dr. Abdias de Menezes',
    municipality: 'Itaberaba',
    uf: 'BA',
    fillingDate: '2025-05-15',
    fillingTime: '09:30',
    student: {
      fullName: 'Carlos Andrade de Souza',
      birthDate: '2010-03-22',
      age: '15',
      grade: '9º Ano',
      shift: 'Matutino',
      enrollmentId: '2010032201',
    },
    guardian: {
      fullName: 'Mariana Andrade de Souza',
      relationship: 'Mãe',
      phone: '(75) 99988-7766',
      address: 'Rua das Flores, 123, Centro, Itaberaba-BA',
    },
    occurrenceDate: '2025-05-14',
    occurrenceTime: '11:00',
    location: 'Pátio da escola',
    occurrenceTypes: [OccurrenceType.VERBAL_AGGRESSION, OccurrenceType.BULLYING],
    detailedDescription: 'Durante o intervalo, o aluno Carlos foi alvo de ofensas verbais e intimidação por parte de um grupo de alunos do mesmo ano. As ofensas eram de cunho pejorativo e contínuo, caracterizando uma situação de bullying. A coordenadora pedagógica presenciou parte do ocorrido e interveio.',
    involvedPeople: 'Carlos Andrade de Souza (vítima), Aluno X, Aluno Y, Aluno Z (agressores), Coordenadora Pedagógica Maria Silva (testemunha).',
    immediateActions: 'Os alunos envolvidos foram encaminhados para a diretoria. Foi realizada uma conversa inicial separadamente com a vítima e os agressores. Os responsáveis de todos os alunos foram contatados por telefone.',
    referrals: 'Agendada reunião com os responsáveis dos alunos agressores. O aluno Carlos foi encaminhado para acompanhamento com a psicóloga da escola. O caso será levado ao Conselho de Classe.',
    socialServiceEvaluation: '',
    status: OccurrenceStatus.IN_PROGRESS,
    createdAt: '2025-05-15T12:30:00Z',
    updatedAt: '2025-05-15T14:00:00Z',
    auditLog: [
      {
        id: 'log-1715894361000',
        timestamp: '2025-05-15T12:30:00Z',
        user: 'Usuário do Sistema',
        action: 'Criação da Ficha',
        details: 'Ficha de ocorrência registrada no sistema.',
      },
      {
        id: 'log-1715894361001',
        timestamp: '2025-05-15T14:00:00Z',
        user: 'Usuário do Sistema',
        action: 'Atualização de Status',
        details: "Status alterado de 'Aberta' para 'Em Andamento'.",
      },
    ],
  },
  {
    id: 'OCC-1715892145',
    schoolUnit: 'Colégio Estadual de Itaberaba',
    municipality: 'Itaberaba',
    uf: 'BA',
    fillingDate: '2025-04-20',
    fillingTime: '15:45',
    student: {
      fullName: 'Juliana Pereira Lima',
      birthDate: '2008-11-10',
      age: '16',
      grade: '2º Ano - Ensino Médio',
      shift: 'Vespertino',
      enrollmentId: '2008111005',
    },
    guardian: {
      fullName: 'Roberto Lima',
      relationship: 'Pai',
      phone: '(75) 98877-6655',
      address: 'Avenida Principal, 456, Bairro Novo, Itaberaba-BA',
    },
    occurrenceDate: '2025-04-20',
    occurrenceTime: '14:20',
    location: 'Corredor próximo à sala 08',
    occurrenceTypes: [OccurrenceType.PHYSICAL_AGGRESSION],
    detailedDescription: 'A aluna Juliana envolveu-se em uma briga com outra aluna, resultando em agressões físicas mútuas (puxões de cabelo e arranhões). A briga foi separada por um professor que passava pelo local. Ambas as alunas apresentavam escoriações leves.',
    involvedPeople: 'Juliana Pereira Lima, Aluna A, Professor João Costa.',
    immediateActions: 'As alunas foram levadas para a enfermaria para os primeiros cuidados. Os pais foram chamados para comparecerem à escola imediatamente. Foi registrada a ocorrência no livro da escola.',
    referrals: 'Reunião com os pais de ambas as alunas foi realizada. As alunas receberam uma suspensão de 3 dias e foram orientadas a realizar uma atividade reflexiva sobre o ocorrido. O caso foi comunicado ao Conselho Tutelar devido à agressão física.',
    socialServiceEvaluation: 'O Serviço Social foi acionado para mediar uma conversa entre as famílias e acompanhar a reintegração das alunas após o período de suspensão.',
    status: OccurrenceStatus.RESOLVED,
    createdAt: '2025-04-20T18:45:00Z',
    updatedAt: '2025-04-25T10:00:00Z',
    auditLog: [
      {
        id: 'log-1715892145000',
        timestamp: '2025-04-20T18:45:00Z',
        user: 'Usuário do Sistema',
        action: 'Criação da Ficha',
        details: 'Ficha de ocorrência registrada no sistema.',
      },
       {
        id: 'log-1715892145001',
        timestamp: '2025-04-25T10:00:00Z',
        user: 'Usuário do Sistema',
        action: 'Atualização de Status',
        details: "Status alterado de 'Aberta' para 'Resolvida'.",
      },
    ],
  },
  {
    id: 'OCC-1715881234',
    schoolUnit: 'Centro Educacional de Itaberaba',
    municipality: 'Itaberaba',
    uf: 'BA',
    fillingDate: '2025-03-10',
    fillingTime: '08:15',
    student: {
      fullName: 'Pedro Henrique Martins',
      birthDate: '2012-01-05',
      age: '13',
      grade: '7º Ano',
      shift: 'Matutino',
      enrollmentId: '2012010502',
    },
    guardian: {
      fullName: 'Ana Lúcia Martins',
      relationship: 'Avó / Responsável Legal',
      phone: '(75) 99911-2233',
      address: 'Rua da Paz, 789, Itaberaba-BA',
    },
    occurrenceDate: '2025-03-09',
    occurrenceTime: '10:30',
    location: 'Sala de aula',
    occurrenceTypes: [OccurrenceType.ESCAPE],
    detailedDescription: 'O aluno Pedro Henrique saiu da sala de aula sem a permissão do professor durante a aula de Matemática e não retornou. Após verificação, constatou-se que ele havia deixado a unidade escolar, pulando o muro dos fundos.',
    involvedPeople: 'Pedro Henrique Martins, Professor Ricardo Alves.',
    immediateActions: 'A família foi comunicada imediatamente sobre o ocorrido. A ronda escolar foi acionada para auxiliar na localização do aluno. A equipe gestora percorreu as ruas próximas à escola.',
    referrals: 'O aluno foi encontrado em casa 2 horas depois. Foi realizada uma reunião com a avó e o aluno para entender os motivos da fuga. O caso foi encaminhado para o CREAS para acompanhamento familiar, pois foi identificado um histórico de evasão.',
    socialServiceEvaluation: '',
    status: OccurrenceStatus.CLOSED,
    createdAt: '2025-03-10T11:15:00Z',
    updatedAt: '2025-03-15T16:20:00Z',
     auditLog: [
      {
        id: 'log-1715881234000',
        timestamp: '2025-03-10T11:15:00Z',
        user: 'Usuário do Sistema',
        action: 'Criação da Ficha',
        details: 'Ficha de ocorrência registrada no sistema.',
      },
      {
        id: 'log-1715881234001',
        timestamp: '2025-03-15T16:20:00Z',
        user: 'Usuário do Sistema',
        action: 'Atualização de Status',
        details: "Status alterado de 'Aberta' para 'Fechada'.",
      },
    ],
  },
  {
    id: 'OCC-1715875432',
    schoolUnit: 'Escola Municipal de Campo Formoso',
    municipality: 'Itaberaba',
    uf: 'BA',
    fillingDate: '2025-02-28',
    fillingTime: '11:00',
    student: {
      fullName: 'Lucas Gabriel Jesus',
      birthDate: '2009-07-15',
      age: '15',
      grade: '9º Ano',
      shift: 'Matutino',
      enrollmentId: '2009071509',
    },
    guardian: {
      fullName: 'Sandra de Jesus',
      relationship: 'Mãe',
      phone: '(75) 98123-4567',
      address: 'Zona Rural, Povoado de Campo Formoso, Itaberaba-BA',
    },
    occurrenceDate: '2025-02-27',
    occurrenceTime: '09:00',
    location: 'Banheiro masculino',
    occurrenceTypes: [OccurrenceType.PROPERTY_DAMAGE, OccurrenceType.OTHER],
    otherOccurrenceType: 'Pichação com palavras de baixo calão',
    detailedDescription: 'O aluno Lucas foi flagrado por um funcionário da limpeza pichando a porta do banheiro masculino com palavras ofensivas a um professor. Além da pichação, a maçaneta da porta foi danificada na tentativa de mantê-la fechada.',
    involvedPeople: 'Lucas Gabriel Jesus, Funcionário José Carlos (testemunha).',
    immediateActions: 'O aluno foi levado à diretoria e confessou o ato. A mãe foi chamada à escola e comunicada sobre o ocorrido e sobre a necessidade de reparo do dano causado.',
    referrals: 'A família se responsabilizou pelos custos do reparo da porta. O aluno foi suspenso por 2 dias e realizou uma atividade de conscientização sobre a importância do patrimônio público.',
    socialServiceEvaluation: '',
    status: OccurrenceStatus.RESOLVED,
    createdAt: '2025-02-28T14:00:00Z',
    updatedAt: '2025-03-05T09:30:00Z',
    auditLog: [
      {
        id: 'log-1715875432000',
        timestamp: '2025-02-28T14:00:00Z',
        user: 'Usuário do Sistema',
        action: 'Criação da Ficha',
        details: 'Ficha de ocorrência registrada no sistema.',
      },
      {
        id: 'log-1715875432001',
        timestamp: '2025-03-05T09:30:00Z',
        user: 'Usuário do Sistema',
        action: 'Atualização de Status',
        details: "Status alterado de 'Aberta' para 'Resolvida'.",
      },
    ],
  },
  {
    id: 'OCC-1715869876',
    schoolUnit: 'Escola Municipal Dr. Abdias de Menezes',
    municipality: 'Itaberaba',
    uf: 'BA',
    fillingDate: '2025-05-20',
    fillingTime: '14:00',
    student: {
      fullName: 'Fernanda Oliveira Santos',
      birthDate: '2011-09-01',
      age: '13',
      grade: '8º Ano',
      shift: 'Vespertino',
      enrollmentId: '2011090103',
    },
    guardian: {
      fullName: 'Carlos Alberto Santos',
      relationship: 'Pai',
      phone: '(75) 99234-5678',
      address: 'Rua Nova, 321, Itaberaba-BA',
    },
    occurrenceDate: '2025-05-20',
    occurrenceTime: '13:30',
    location: 'Portão da escola',
    occurrenceTypes: [OccurrenceType.SOCIAL_RISK],
    detailedDescription: 'A aluna Fernanda tem apresentado sonolência excessiva, falta de higiene e hematomas leves nos braços. Ao ser questionada de forma reservada pela orientadora educacional, relatou um ambiente familiar conturbado e situações de negligência em casa.',
    involvedPeople: 'Fernanda Oliveira Santos, Orientadora Educacional Carla Nunes.',
    immediateActions: 'A aluna foi acolhida em um espaço seguro na escola. O Conselho Tutelar foi acionado imediatamente via telefone e e-mail formalizando a denúncia de suspeita de negligência e vulnerabilidade social.',
    referrals: 'O caso foi oficialmente encaminhado para o Conselho Tutelar para investigação e acompanhamento da família. A aluna será acompanhada pela equipe de psicologia da rede municipal.',
    socialServiceEvaluation: 'O serviço social da escola está atuando como ponto de apoio para o Conselho Tutelar e monitorando o bem-estar da aluna na unidade escolar.',
    status: OccurrenceStatus.OPEN,
    createdAt: '2025-05-20T17:00:00Z',
    updatedAt: '2025-05-20T17:00:00Z',
    auditLog: [
      {
        id: 'log-1715869876000',
        timestamp: '2025-05-20T17:00:00Z',
        user: 'Usuário do Sistema',
        action: 'Criação da Ficha',
        details: 'Ficha de ocorrência registrada no sistema.',
      },
    ],
  },
];